---
version: 3
dependencies:
  ansible_core:
    package_pip: ansible-core==2.15.1
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements.yml
  python_interpreter:
    package_system: "python310"
    python_path: "/usr/bin/python3.10"
  python:
    - pypsrp
    - requests[socks]
    - PySocks

images:
  base_image:
    name: registry.fedoraproject.org/fedora:39  # vanilla image!

additional_build_steps:
  prepend_final:
    - RUN sudo yum install -y https://s3.amazonaws.com/session-manager-downloads/plugin/latest/linux_64bit/session-manager-plugin.rpm
